[phases.setup]
runtime = "php@8.3"

[phases.build]
commands = [
    "composer install --optimize-autoloader",
    "npm install",
    "npm run build",
    "php artisan migrate --seed --force",
    "php artisan optimize",
    "chmod 777 -R storage/",
    "chmod 777 -R bootstrap/cache",
    "php artisan storage:link"
]
